title: Matemática Computacional
author:  Artur Fassoni
copyright: "2026"
logo: "_static/logo.svg"

repository:
  url: https://github.com/arturfassoni/mat034
  branch: main

execute:
  execute_notebooks: cache  # "off" para o GitHub compilar rápido sem rodar todos os códigos do zero

sphinx:
  config:
    language: pt
    html_theme_options:
      toc_title: " "
      home_page_in_toc: false  # Oculta a home do menu lateral

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath